name: Release Package

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v4.1.1
    - name: Setup .NET
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: 5.0.100
    - name: Restore tools
      run: dotnet tool restore
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./fable/Feliz.ReactSpeedometer
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ./fable/Feliz.ReactSpeedometer
    - name: Pack
      run: dotnet pack --configuration Release --no-build --output -p:PackageVersion=${{ github.ref_name }} -p:PackageReleaseNotes=${{ github.event.release.html_url }} .
      working-directory: ./fable/Feliz.ReactSpeedometer
    - name: Publish
      run: dotnet nuget push "*.nupkg" --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
      working-directory: ./fable/Feliz.ReactSpeedometer
